source :rubygems

gem "sinatra"
gem "haml"
gem "thin", :require => false
gem "faraday_middleware"
gem "simple_oauth"

gem "her", :path => File.join(File.dirname(__FILE__),"../..")

group :development do
  gem "shotgun"
end
