require 'portugal/tasks'
Portugal.configure do |config|
  config.migrations_path = File.expand_path("../db/migrations", __FILE__)
end

# This task is called before Portugal executes its tasks.
# It should require ActiveRecord somehow and establish the database connection
#
# Change it so it works for your application
task :environment do
  require 'bundler'
  Bundler.require
  ActiveRecord::Base.establish_connection adapter: 'sqlite3', database: File.expand_path('../db/development.db', __FILE__)
end
